services:
  - type: web
    name: swingleofy-ai-stocks
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    port: 3000
    envVars:
      - key: NODE_ENV
        value: production
